### ISSUE TITLE
Hit flash on damage application

### ISSUE THREAD

**Issue by odecay** [fishfolk/punchy#267]
### Description

Flash sprite in damage application system, by setting [sprite color]( https://docs.rs/bevy/latest/bevy/sprite/struct.Sprite.html#structfield.color) to white.

This will provide visual feedback of damage application, and not require unique hand animated frames from artists.

**Comment by Zac8668** [comment]
I think maybe this can be closed? With the #286 merge

**Comment by odecay** [comment]
complete
