### ISSUE TITLE
Implement boss bomb throwing

### ISSUE THREAD

**Issue by odecay** [fishfolk/punchy#269]
Boss bomb attack.
Attack should throw projectile bombs in an arc which land on the ground some distance away, after a short delay or upon collision they should explode causing AOE damage and Knockback state to players in radius.

- [ ] Find bomb spritesheet from Jumpy
- [ ] Implement state for bosses bomb throw attack
- [ ] Add attack to boss YAML

Check bottle throw for projectile reference.

**Comment by zicklag** [comment]
>  Find bomb spritesheet from Jumpy

See the `kick_bomb.png` and `explosion.png` in this folder:

https://github.com/fishfolks/jumpy/tree/main/assets/map/elements/item/kick_bomb

**Comment by Zac8668** [comment]
I'll claim this one

**Comment by zicklag** [comment]
Oh, FYI there are a couple more explosions here, too:

https://github.com/fishfolk/jumpy/tree/main/old_assets/textures/explosions

Just in case you need a different size.
