### ISSUE TITLE
Interactable Items

### ISSUE THREAD

**Issue by odecay** [fishfolk/punchy#27]
Items defined in asset system and systems which allow them to be interacted with.

- [x] #83
- [x] #84
- [x] #85
- [x] #86

**Comment by Zac8668** [comment]
I think this can be closed, or should we aim for a new intractable item? Next that comes to mind would be a explosive

**Comment by erlend-sh** [comment]
It’d be great to have a Items wiki page to wrap this up 💝 

Additional items to-be-added can have dedicated issues posted.
